# Generated by Django 4.0.6 on 2022-10-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='Files/')),
                ('tech_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageApp.categories')),
            ],
        ),
    ]
