# Generated by Django 4.0.6 on 2022-10-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0003_profile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='Files/')),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('ratings', models.IntegerField()),
            ],
        ),
    ]
